[package]
name = "invite_code_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net"] }
axum = "0.8.9"
tower-http = { version = "0.7.1", features = ["cors", "trace"] }
tower-sessions = { version = "0.15.0", features = ["signed"] }
serde = { version = "1.0.229", features = ["derive"] }
dotenvy = "0.15.7"
diesel = { version = "2.3.13", features = ["sqlite"] }
deadpool-diesel = { version = "0.7.0", features = ["sqlite"] }
rand = "0.10.3"
totp-rs = { version = "5.7.2", features = ["gen_secret"] }
reqwest = { version = "0.13.5", default-features = false, features = [
    "json",
    "query",
    "rustls",
] }
rpassword = "7.5.4"
rust-argon2 = "3.0.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
utoipa = { version = "5.5.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", default-features = false, features = [
    "axum",
    "vendored",
] }
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
serde_json = "1.0.151"
time = "0.3.55"

[dev-dependencies]
serde_json = "1.0.151"
tower = { version = "0.5.3", features = ["util"] }

[profile.dev]
debug = "line-tables-only"

[profile.release]
strip = "symbols"

[package.metadata.tarpaulin]
exclude-files = [
    "src/schema.rs",
]
ignore-panics = true
